CREATE TABLE IF NOT EXISTS `inspect_config_baseline` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `app_system_id` bigint NOT NULL COMMENT '应用ID',
  `app_module_id` bigint DEFAULT NULL COMMENT '应用模块ID',
  `env_id` bigint DEFAULT NULL COMMENT '环境ID',
  `type_id` bigint DEFAULT NULL COMMENT '资源模型ID',
  `schema_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '基线数据结构名称，如os/nginx/tomcat',
  `scope_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '作用域哈希',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '基线名称',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '说明',
  `current_version_id` bigint DEFAULT NULL COMMENT '当前激活版本ID',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_scope_hash` (`scope_hash`) USING BTREE,
  KEY `idx_app_system_id` (`app_system_id`) USING BTREE,
  KEY `idx_app_module_id` (`app_module_id`) USING BTREE,
  KEY `idx_env_id` (`env_id`) USING BTREE,
  KEY `idx_type_id` (`type_id`) USING BTREE,
  KEY `idx_current_version_id` (`current_version_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对基线';

CREATE TABLE IF NOT EXISTS `inspect_config_ai_setting` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `view_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用清单入口视图名',
  `model_id` bigint NOT NULL COMMENT 'AI模型ID',
  `prompt` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'AI提示词',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_view_name` (`view_name`) USING BTREE,
  KEY `idx_model_id` (`model_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对AI模型设置';

CREATE TABLE IF NOT EXISTS `inspect_config_baseline_version` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `baseline_id` bigint NOT NULL COMMENT '基线ID',
  `version` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '版本号',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '状态：draft/pending_approval/approved/active/rejected',
  `is_frozen` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否冻结',
  `source_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '来源类型：snapshot/promote/manual',
  `source_snapshot_id` bigint DEFAULT NULL COMMENT '来源快照ID',
  `source_resource_id` bigint DEFAULT NULL COMMENT '来源资产ID',
  `field_count` int DEFAULT NULL COMMENT '基线字段数',
  `baseline_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '基线数据',
  `ai_candidate_data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'AI候选筛选结果',
  `change_summary` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '变更摘要',
  `change_log` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '变更日志',
  `submitter` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '提交人',
  `submit_time` timestamp(3) NULL DEFAULT NULL COMMENT '提交时间',
  `approval_status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审批状态：pending/approved/rejected',
  `approver` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审批人',
  `approval_comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '审批意见',
  `approved_time` timestamp(3) NULL DEFAULT NULL COMMENT '审批通过时间',
  `activated_time` timestamp(3) NULL DEFAULT NULL COMMENT '激活时间',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_baseline_version` (`baseline_id`,`version`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE,
  KEY `idx_submitter` (`submitter`) USING BTREE,
  KEY `idx_approval_status` (`approval_status`) USING BTREE,
  KEY `idx_approver` (`approver`) USING BTREE,
  KEY `idx_source_snapshot_id` (`source_snapshot_id`) USING BTREE,
  KEY `idx_source_resource_id` (`source_resource_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对基线版本';

CREATE TABLE IF NOT EXISTS `inspect_config_snapshot` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `app_system_id` bigint NOT NULL COMMENT '应用ID',
  `app_module_id` bigint DEFAULT NULL COMMENT '应用模块ID',
  `env_id` bigint DEFAULT NULL COMMENT '环境ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `type_id` bigint DEFAULT NULL COMMENT '资源模型ID',
  `job_id` bigint DEFAULT NULL COMMENT '采集作业ID',
  `schema_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '快照数据结构名称，如os/nginx/tomcat',
  `schema_version` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '快照结构版本',
  `source` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '来源：inspect_app/inspect/manual',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '快照状态：succeed/failed',
  `collect_time` timestamp(3) NOT NULL COMMENT '采集时间',
  `config_file_audit_id` bigint DEFAULT NULL COMMENT '配置文件审计ID',
  `raw_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '原始采集数据',
  `normalized_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '规范化快照数据',
  `ai_candidate_data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'AI候选筛选结果',
  `ai_draft_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'AI辅助后的基线草稿',
  `summary` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '快照摘要',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_app_system_id` (`app_system_id`) USING BTREE,
  KEY `idx_app_module_id` (`app_module_id`) USING BTREE,
  KEY `idx_env_id` (`env_id`) USING BTREE,
  KEY `idx_resource_id` (`resource_id`) USING BTREE,
  KEY `idx_job_id` (`job_id`) USING BTREE,
  KEY `idx_collect_time` (`collect_time`) USING BTREE,
  KEY `idx_schema_name` (`schema_name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对快照';

CREATE TABLE IF NOT EXISTS `inspect_config_compare_task` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `compare_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '比对类型：baseline/peer',
  `baseline_version_id` bigint DEFAULT NULL COMMENT '基线版本ID',
  `source_snapshot_id` bigint NOT NULL COMMENT '源快照ID',
  `target_snapshot_id` bigint DEFAULT NULL COMMENT '目标快照ID',
  `app_system_id` bigint NOT NULL COMMENT '应用ID',
  `app_module_id` bigint DEFAULT NULL COMMENT '应用模块ID',
  `env_id` bigint DEFAULT NULL COMMENT '环境ID',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '任务状态：pending/running/succeed/failed',
  `compare_result` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '结果：compliant/noncompliant',
  `risk_level` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '风险等级',
  `is_blocked` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否阻断',
  `total_count` int DEFAULT NULL COMMENT '总项数',
  `diff_count` int DEFAULT NULL COMMENT '差异项数',
  `high_count` int DEFAULT NULL COMMENT '高风险差异数',
  `medium_count` int DEFAULT NULL COMMENT '中风险差异数',
  `low_count` int DEFAULT NULL COMMENT '低风险差异数',
  `summary` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '比对摘要',
  `ai_summary` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'AI解释摘要',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_baseline_version_id` (`baseline_version_id`) USING BTREE,
  KEY `idx_source_snapshot_id` (`source_snapshot_id`) USING BTREE,
  KEY `idx_target_snapshot_id` (`target_snapshot_id`) USING BTREE,
  KEY `idx_app_system_id` (`app_system_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对任务';

CREATE TABLE IF NOT EXISTS `inspect_config_compare_detail` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `task_id` bigint NOT NULL COMMENT '比对任务ID',
  `layer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '层级：hardware/kernel/os/application',
  `path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段路径',
  `label` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字段名称',
  `compare_mode` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '比对模式：exact/set/object_by_key/kv_map/regex/range',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '明细状态：different/missing/additional/ignored',
  `risk_level` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '风险等级',
  `is_blocked` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否阻断',
  `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '差异原因',
  `source_value` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '源值',
  `target_value` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '目标值',
  `sort` int DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_task_id` (`task_id`) USING BTREE,
  KEY `idx_layer` (`layer`) USING BTREE,
  KEY `idx_path` (`path`) USING BTREE,
  KEY `idx_risk_level` (`risk_level`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对明细';

CREATE TABLE IF NOT EXISTS `inspect_config_rule` (
  `id` bigint NOT NULL COMMENT '唯一标识',
  `baseline_id` bigint NOT NULL DEFAULT '0' COMMENT '基线ID，0代表全局规则',
  `layer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '层级：hardware/kernel/os/application',
  `path_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '路径哈希',
  `path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段路径',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段名称',
  `compare_mode` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '比对模式：exact/set/object_by_key/kv_map/regex/range',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否必选',
  `is_ignore` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否忽略',
  `risk_weight` int NOT NULL DEFAULT '0' COMMENT '风险权重',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `config` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '规则配置',
  `fcd` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `fcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `lcd` timestamp(3) NULL DEFAULT NULL COMMENT '修改时间',
  `lcu` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_baseline_path_hash` (`baseline_id`,`path_hash`) USING BTREE,
  KEY `idx_layer` (`layer`) USING BTREE,
  KEY `idx_compare_mode` (`compare_mode`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='巡检配置比对规则';
